# Generated by Django 5.2.8 on 2026-07-01 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=255)),
                ('user_role', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('req_type', models.CharField(max_length=20)),
                ('req_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='banking.user')),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=20)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='banking.user')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
